// <auto-generated />
namespace CanakkaleBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class forenkeyolusturma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forenkeyolusturma));
        
        string IMigrationMetadata.Id
        {
            get { return "202212141021203_forenkeyolusturma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
